### ISSUE TITLE
Unable to find pkg=com.spotify.music

### ISSUE THREAD

**Issue by pinguluk** [shinyford/nowplaying#9]
Hello, I'm getting this error when I change a song.

```dart
import 'dart:async';
import 'dart:developer';

import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:nowplaying/nowplaying.dart';

class NowPlayingService extends GetxService {
  static NowPlayingTrack? track;

  Future<NowPlayingService> init() async {
    debugPrint('NowPlayingService init');

    NowPlaying.instance.start();
    NowPlaying.instance.isEnabled().then((bool isEnabled) async {
      if (!isEnabled) {
        final shown = await NowPlaying.instance.requestPermissions();
        debugPrint('MANAGED TO SHOW PERMS PAGE: $shown');
      }
    });

    NowPlaying.instance.stream.listen((value) {
      track = value;
      inspect(track);
    });

    return this;
  }
}
```

```
E/Icon    ( 5810): Unable to find pkg=com.spotify.music for icon Icon(typ=RESOURCE pkg=com.spotify.music id=0x7f0802f1)
E/Icon    ( 5810): android.content.pm.PackageManager$NameNotFoundException: com.spotify.music
E/Icon    ( 5810): 	at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:423)
E/Icon    ( 5810): 	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:412)
E/Icon    ( 5810): 	at android.graphics.drawable.Icon.loadDrawableInner(Icon.java:366)
E/Icon    ( 5810): 	at android.graphics.drawable.Icon.loadDrawable(Icon.java:334)
E/Icon    ( 5810): 	at com.gomes.nowplaying.NowPlayingPlugin.convertIcon(NowPlayingPlugin.java:240)
E/Icon    ( 5810): 	at com.gomes.nowplaying.NowPlayingPlugin.extractFieldsFor(NowPlayingPlugin.java:207)
E/Icon    ( 5810): 	at com.gomes.nowplaying.NowPlayingPlugin.access$000(NowPlayingPlugin.java:37)
E/Icon    ( 5810): 	at com.gomes.nowplaying.NowPlayingPlugin$ChangeBroadcastReceiver.onReceive(NowPlayingPlugin.java:145)
E/Icon    ( 5810): 	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1556)
E/Icon    ( 5810): 	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
E/Icon    ( 5810): 	at android.os.Handler.handleCallback(Handler.java:938)
E/Icon    ( 5810): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/Icon    ( 5810): 	at android.os.Looper.loop(Looper.java:223)
E/Icon    ( 5810): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/Icon    ( 5810): 	at java.lang.reflect.Method.invoke(Native Method)
E/Icon    ( 5810): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/Icon    ( 5810): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by pinguluk** [comment]
Fixed by adding Android 11 permissions 
Read more here: https://github.com/shinyford/nowplaying/pull/11
